### ISSUE TITLE
Axios interceptorları ile X-AccessToken yollanamalı ve Failed olması durumunda hata bastırılmalı (Tüm hatalar da interceptor üzerinden bastırılabilir)

### ISSUE THREAD

**Issue by DEONSKY** [mavidurak/mentor-front-end-vue#109]
Zamanında amele gibi copy past yapmışız :). İleride kolay değişiklik yapabilmemiz bu işlemleri tek yerden ayarlayabiliriz

**Comment by teathedev** [comment]
Hataları izleyecek global bir component olması gerekiyor ki kullanıcıya bu hataları gösterebilelim. Bu hataları sweetalert olarak render edebiliriz. Token kısmında haklısın.

**Comment by DEONSKY** [comment]
https://axios-http.com/docs/interceptors
