### ISSUE TITLE
Yeni Üyelik formu çalışmıyor.

### ISSUE THREAD

**Issue by ozziest** [mavidurak/mentor-front-end-vue#38]
Form verisi ve JS tarafında aldığımız hata bu şekilde;

![image](https://user-images.githubusercontent.com/2325140/95651037-065b2f00-0af0-11eb-89c3-63647809a01f.png)

Sorunun ana kaynağı şu; dönen hata mesajının formatı beklediğimiz gibi değil.

![image](https://user-images.githubusercontent.com/2325140/95651070-2d196580-0af0-11eb-8697-f89703b7bc31.png)

**Comment by saracalihan** [comment]
OS: **Linux 5.10.31 - Manjaro**
Browser: **Google Chrome 90.0.4430.93 (64-bit)**
Result: **Working as well**

---

**Interface**:
![Screenshot_20210505_234237](https://user-images.githubusercontent.com/56413673/117206774-ed073080-adfb-11eb-97bf-cb49a24b5ea3.png)

**Database**:
![Screenshot_20210505_234944](https://user-images.githubusercontent.com/56413673/117207518-b2ea5e80-adfc-11eb-8d0f-3324b81729f9.png)

**Comment by DEONSKY** [comment]
OS: Ubuntu 20.04.2 LTS (Focal Fossa)
Browser: Chrome Version 89.0.4389.82 (Official Build) (64-bit)
Result: Working as Well

New registration:
![Ekran Alıntısı](https://user-images.githubusercontent.com/56413725/117655027-36aa9f00-b19f-11eb-87f4-6ced595044f5.PNG)

Login after registration:
![Ekran Alıntısı2](https://user-images.githubusercontent.com/56413725/117655090-4924d880-b19f-11eb-97d6-aec2c47b1020.PNG)

Trying to re-registration with same parameters
![Ekran Alıntısı3](https://user-images.githubusercontent.com/56413725/117655372-a6208e80-b19f-11eb-87da-5a997d9f524b.PNG)
