### ISSUE TITLE
Çıkış yapma sorunu

### ISSUE THREAD

**Issue by saracalihan** [mavidurak/mentor-front-end-vue#40]
Kullanıcı çıkış yaptıktan sonra tarayıcı üzerindeki "geri" tuşuna basarsa login sayfasına yönlendirmek yerine doğrudan bir önceki sayfaya yönlendiriyor.Token local storage'dan silindiği için geri gelince sadece verisi olmayan bir arayüz görüyor.

**Comment by DEONSKY** [comment]
Hallettim

**Comment by saracalihan** [comment]
`4de441916dc6b2a6df0e8425beb54bc60f68054b` commiti ile çözüldü.
