### ISSUE TITLE
DataSet oluşturma ve güncelleme formu çalışmıyor.

### ISSUE THREAD

**Issue by teathedev** [mavidurak/mentor-front-end-vue#47]
`key_title` alanı `data_type` olarak değiştirildiği için hata veriyor. Ayrıca data type alanı seçildiğinde 2 kere seçiyor. Çoklu seçim engellenmeli.

**Comment by DEONSKY** [comment]
Bu issue ya bakıyorum

**Comment by saracalihan** [comment]
https://github.com/mavidurak/mentor-front-end/pull/51
