### ISSUE TITLE
Navbar güncellenmesi

### ISSUE THREAD

**Issue by teathedev** [mavidurak/mentor-front-end-vue#48]
Soldaki menüye "Datasets, Datas ve Applications" için itemlar oluşturulmalı. Bu itemların hepsinin altında "Yeni Kayıt Oluştur" ve "Listeyi Gör" seçenekleri olacak.

**Comment by teathedev** [comment]
Ayrıca Profil linki Dashboard içerisinden silinmeli.

**Comment by DEONSKY** [comment]
Bundan önce navbarla ilgilendindiğim için üzerinde çalışmaya karar verdim. Bu sayfalar daha oluşturulmadığı için herbirini yeni oluşturacağım boş sayfalara yönlendirecem
