### ISSUE TITLE
Formlarda input'ta enter'a basildiginda doldurulmasi gereken baska bir input varsa focus siradaki input'a gecmeli

### ISSUE THREAD

**Issue by teathedev** [mavidurak/mentor-front-end-vue#53]
Ornegin giris yaparken e-posta girildikten sonra enter'a basilir ve e-posta validasyonu gecerse focus password input'una gecmeli

**Comment by DEONSKY** [comment]
İlgilenecem

**Comment by DEONSKY** [comment]
Component şeklinde inputları eklediğim için internette bulduğum yöntemler işe yaramıyor. Daha fazla vakit ayırırsan bir şekilde çözerim. Bu özellik çok gerekli mi ? . Twitterda filan denedim. Onlarda otomatik alta geçmiyor
