### ISSUE TITLE
Form validasyonlari deger degistiginde yapilmamali

### ISSUE THREAD

**Issue by teathedev** [mavidurak/mentor-front-end-vue#55]
Validasyonlar inputun degeri her degistigi zaman yapilmamali. Input focusu kaybeder veya gonderme butonuna tiklanirsa yapilmali. Eger hata mesaji gosterildikten sonra input degeri degisirse hata mesaji kaybolmali ve bir sonraki validasyon yapildiginda geri gelmeli (eger hata varsa)

**Comment by DEONSKY** [comment]
İlgilenecem

**Comment by DEONSKY** [comment]
Halledildi
