### ISSUE TITLE
Form validasyon hatalarinin gosterimi

### ISSUE THREAD

**Issue by teathedev** [mavidurak/mentor-front-end-vue#56]
- [x] Hata alinan input'larin cercevesi kirmizi olabilir. Hangi alanin hata verdigini daha net gostermek gerekiyor.
- [x] Hata mesajlari input'lara yapisik geliyor. Biraz bosluk eklenebilir.
- [x] Kayit olma ekraninda hata mesajlarinin renkleri yok.

**Comment by DEONSKY** [comment]
İlgilenecem

**Comment by DEONSKY** [comment]
Halledildi
