### ISSUE TITLE
Sabit inputlar icin componentler hazirlanmasi

### ISSUE THREAD

**Issue by teathedev** [mavidurak/mentor-front-end-vue#57]
Sabit inputlar icin (ornegin e-posta, sifre ve kullanici adi gibi) componentler hazirlanip bunlari login, register, forgot password gibi alanlarda kullanabiliriz.
Bunun yaninda duz metinler icin de sade bir input ile min max validasyonu olan bir input hazirlayabiliriz. Input validasyonlarini yonetmek daha kolay olabilir bu sekilde.

**Comment by DEONSKY** [comment]
İlgilenecem

**Comment by DEONSKY** [comment]
Halledildi

**Comment by DEONSKY** [comment]
+ Olarak eposta, sifre,kullanıcı adı, gerçek ad gibi özellikler tek bir componentte toplanabilir gibi geldi bana. Proplar oluşturup sadece değişen değerleri atayarak input oluşturulabilir.
