### ISSUE TITLE
API isteklerindeki domain kaldirilmali.

### ISSUE THREAD

**Issue by teathedev** [mavidurak/mentor-front-end-vue#58]
axios isteklerinde (bkz: https://github.com/mavidurak/mentor-front-end/blob/master/src/views/Guests/Login.vue 92.satir) domain ile birlikte istek atiliyor.

Bu yanlis bir ilerleyis. Eger bu sekilde kullanirsak production, staging icin veya gelistirme ortaminda API'yi farkli portta calistirdigimiz zaman butun dosyalarda bunu degistirmemiz gerekecek. 

Bu durumu engellemek icin vue.config.js'e daha onceden proxy eklemistik. Butun isteklerdeki domain ibaresini (http://localhost:4000) silersek eger otomatik olarak istekler proxy ile oraya yonlendirilecek.

**Comment by DEONSKY** [comment]
Hallederim

**Comment by DEONSKY** [comment]
Hallettim
