### ISSUE TITLE
Applications görüntüleme güncellenecek

### ISSUE THREAD

**Issue by saracalihan** [mavidurak/mentor-front-end-vue#66]
görüntüleme ve silme aynı view olacak

**Comment by DEONSKY** [comment]
Backenddeki değişikliklere göre hareket edecem

**Comment by teathedev** [comment]
https://github.com/mavidurak/mentor-api/issues/64 ve https://github.com/mavidurak/mentor-api/issues/67 issue'larına göre yapılabilir
