### ISSUE TITLE
Applications oluşturma güncellenecek

### ISSUE THREAD

**Issue by saracalihan** [mavidurak/mentor-front-end-vue#67]
oluşturma ve güncelleme aynı view'ı kullanacak

**Comment by DEONSKY** [comment]
Backenddeki değişikliklere göre hareket edecem

**Comment by teathedev** [comment]
Applications tablosundaki dataSetId alanı kaldırılacak. DataSet tablosuyla "Many to Many" ilişki kurulacak. Buna göre sidebar'dan "Applications -> Create" olarak oluşturma sayfasına giderek Application oluşturulabilinir. Bunun yanında oluşturma alanında multiselect ile çoklu dataset seçimi yaptırılması gerekiyor. Seçilen DataSet'ler "dataSets" keyi ile id'lerini array olarak gönderilen veriye eklenecek.

**Comment by saracalihan** [comment]
https://github.com/mavidurak/mentor-api/issues/64 ile birlikte yapılacak
