### ISSUE TITLE
Data oluşturma sayfası

### ISSUE THREAD

**Issue by saracalihan** [mavidurak/mentor-front-end-vue#69]

**Comment by DEONSKY** [comment]
1. Data oluşturken ayrı bir sayfa yerine liste sayfasına gizlenmiş bir form ile ekleme yapılabilir gibi geldi. Sadece şu anda value ekleyecez çünkü.
2.  Aslında data oluşturma işini hep iot cihazlar halledeceği için frontend arayüzüyle data ekleyebiliyor olmaya gerek var mı?
Bunu yerine sisteme Web Kullanıcılarının Dataset+Datas yada Datas şeklinde yükleme yapabilmesi kullanışlı olacak gibi geliyor bana. Örneğin ellerindeki bir json dosyasını sürükle bırak yapararak tüm dataları yüklemek daha pratik olur

**Comment by teathedev** [comment]
Bunu yapmak için farklı bir yöntem düşünmemiz gerekecek büyük ihtimalle ama şu an ihtiyaç ne şekilde onun bir öngörümünü yapamıyorum. Test ederken ve kullanırken ihtiyaç şekillenir ona göre düzenleriz. Bunun yanında tüm sistemdeki işleyip sayfalar üzerindeyken pop-up tarzında bir mekanizmayı buraya eklemek bence sağlıklı değil. İşleyişi değiştirmek kullanıcıya farklı alışkanlıkları karışık vermek sıkıntı olabilir. Tek standart üzerinden gitmekte fayda var bence şu an
